apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: 99-bottles
spec:
  environments:
    - name: dev
      build:
        from: master
    - name: prod
  components:
    - name: main
      src: "."
      publicPort: http
      ports:
       - name: http
         port: 8080
      environmentConfig:
        - environment: dev
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
